### ISSUE TITLE
Validar el campo nombre

### ISSUE THREAD

**Issue by ghost** [VictorMaJa/trivia-tema-procrastinaci-n#1]
**El campo nombre debe ser obligatorio**

El programa esta acpetando el vacio como nombre

_Agrega el siguiente codigo antes de la linea 6 para solucionar_

![image](https://user-images.githubusercontent.com/26263355/190283906-f106099b-fb81-43fe-b742-3221b188f46d.png)

👇🏻
![image](https://user-images.githubusercontent.com/26263355/190284218-a8850965-0c38-4235-b22a-ba3dfddd33f0.png)

![image](https://user-images.githubusercontent.com/26263355/190283683-0920192e-319a-4818-82aa-1b89a42d852d.png)

Saludos

**Comment by VictorMaJa** [comment]
### SE AGREGO LA VALIDACIÓN DEL NOMBRE !
![issues 1](https://user-images.githubusercontent.com/113326698/190545395-5d043187-15c9-4292-af3c-1558ebccd1b7.png)

**Como se puede visualizar ya hace la validación el nombre OBLIGATORIO ingresando el código.**
![issues 2](https://user-images.githubusercontent.com/113326698/190545468-578a1e71-b07c-465e-9e2c-41a04c21c8de.png)

**Aqui se aprecia en la imagen !**
![issues 3](https://user-images.githubusercontent.com/113326698/190545590-deb60bc9-b696-4384-b39d-87bbd0efd45e.png)

Gracias
 Saludos.
