### ISSUE TITLE
Validar el número de intentos.

### ISSUE THREAD

**Issue by ghost** [VictorMaJa/trivia-tema-procrastinaci-n#2]
**Valide el número de intentos en cada respuesta**

Como se aprecia en la imagen el número de intentos cuando el usuario ingresa una alternativa diferente a las establecidas es ilimitada. 
_Podría agregar un límite de tres intentos o simplemente reconocer la alternativa mal ingresada cómo incorrecta_.
![IMG_20220916_180421](https://user-images.githubusercontent.com/26263355/190828867-2d51b306-3ccb-4d37-8c8e-634cca406afd.jpg)

**Comment by VictorMaJa** [comment]
Hola Elias me podría ayudar con el código estoy intentando ingresar el código correcto pero me sale error !!!

**Comment by VictorMaJa** [comment]
Hola Elias se observa en la imagen, que se estableció el numero de intentos en este caso fue un máximo de 3 intentos
Automáticamente te reporta un mensaje: "Se ha superado el numero de intentos" 

![iss](https://user-images.githubusercontent.com/113326698/190940934-2beedc15-6829-497c-be2b-d713a39a96f2.png)

Como se puede apreciar en el código se ingreso un while para que ejecute la validación y posteriormente ingrese un if para que ejecute y cumpla la condición del mensaje.
![isss](https://user-images.githubusercontent.com/113326698/190941237-df5392d1-2e90-4595-892a-4785af6f2a93.png)

Saludos.
