### ISSUE TITLE
Agrega colores y estilos a los mensajes de pantalla 

### ISSUE THREAD

**Issue by ghost** [VictorMaJa/trivia-tema-procrastinaci-n#3]
### Podrías agregar colores según el tipo de mensaje en la consola.

Para ello primero declara variables globales en la parte superior de la siguiente manera:

`AZUL= '\033[94m'`
`FIN= '\033[0m'`

Y utiliza ese variables en las funciones **print**

`print(AZUL,tumensaje, FIN)`

**Comment by VictorMaJa** [comment]
Se agrego en las líneas de comando los colores asignados!
![colores issues](https://user-images.githubusercontent.com/113326698/190948625-0a27f5c9-6ff6-4b16-acef-073764421c39.png)

Se observa que se agregaron los colores perfectamente en cada opción realizada.
![colores issues 2](https://user-images.githubusercontent.com/113326698/190948717-d659d76a-259b-4252-ad45-91764641db77.png)


Gracias Elias
Saludos
